In [68]:
import numpy as np
import pandas as pd
fp = pd.read_csv("0050.csv")

df = pd.DataFrame({"Open":list(fp["Open"]), 
                   "High":list(fp["High"]), 
                   "Low":list(fp["Low"]), 
                   "Close":list(fp["Close"]), 
                   "Amount":list(fp["Amount"])}, 
                  index = fp["Date"])

conditions = df["Open"] > df["Close"]
df2 = df[conditions]

df3 = df2.sort_values("Amount", ascending=[False])
print(df3)

print()

L = []
for i in range(3):
    a = []
    a.append(int(df3["Open"][i]))
    a.append(int(df3["High"][i]))
    a.append(int(df3["Low"][i]))
    a.append(int(df3["Close"][i]))
    a.append(int(df3["Amount"][i]))
    L.append(a)
    
Arr = np.array(L,dtype = np.int64)
print("array({} ,dtype={})".format(L,Arr.dtype))

#addition
#就這麼印出來了 有夠神奇
Arr.reshape(3,5)
print("array({},dtype={})".format(Arr,Arr.dtype))

             Open   High    Low  Close  Amount
Date                                          
2011/8/5    55.70  55.70  54.45  54.45   93525
2011/8/8    54.30  54.65  51.40  53.50   88159
2018/10/11  80.15  80.15  77.35  77.40   68552
2020/3/19   71.00  71.00  67.25  68.55   68038
2011/9/23   50.50  50.85  49.93  50.35   64026
...           ...    ...    ...    ...     ...
2019/10/21  87.95  88.00  87.75  87.85    1078
2017/10/24  84.50  84.50  84.20  84.40    1072
2017/11/24  85.25  85.30  84.95  85.15    1069
2017/11/14  84.30  84.30  83.95  84.15    1016
2017/11/8   85.20  85.20  84.95  84.95     810

[1122 rows x 5 columns]

array([[55, 55, 54, 54, 93525], [54, 54, 51, 53, 88159], [80, 80, 77, 77, 68552]] ,dtype=int64)
array([[   55    55    54    54 93525]
 [   54    54    51    53 88159]
 [   80    80    77    77 68552]],dtype=int64)
